# Generated by Django 5.0.2 on 2024-03-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='category',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='movies',
            name='director_name',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='movies',
            name='hero_name',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='movies',
            name='heroin_name',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie_title',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='movies',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
