# Generated by Django 5.0.2 on 2024-03-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerapp', '0002_alter_movies_category_alter_movies_director_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='category',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='movies',
            name='director_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='movies',
            name='hero_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='movies',
            name='heroin_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie_title',
            field=models.CharField(max_length=250),
        ),
    ]
