# Generated by Django 5.0.2 on 2024-03-05 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerapp', '0003_alter_movies_category_alter_movies_director_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_type', models.CharField(choices=[('Action Movies', 'Action Movies'), ('Family Entertainent', 'Family Entertainment'), ('Horror Movies', 'Horror Movies'), ('Thriller Movies', 'Thriller Movies'), ('Science Fiction (Sci-Fi) Movies', 'Science Fiction (Sci-Fi) Movies'), ('Romance Movies', 'Romance Movies'), ('Fantasy Movies', 'Fantasy Movies'), ('Animation Movies:', 'Animation Movies:')], max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='movies',
            name='movie_genres',
            field=models.ForeignKey(default=0.041666666666666664, on_delete=django.db.models.deletion.CASCADE, to='registerapp.genres'),
            preserve_default=False,
        ),
    ]
