# Generated by Django 5.0.2 on 2024-03-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerapp', '0004_genres_alter_users_phone_number_movies_movie_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genres',
            name='movie_type',
            field=models.CharField(choices=[('ActionMovies', 'Action Movies'), ('FamilyEntertainment', 'Family Entertainment'), ('HorrorMovies', 'Horror Movies'), ('ThrillerMovies', 'Thriller Movies'), ('ScienceFiction (Sci-Fi) Movies', 'Science Fiction (Sci-Fi) Movies'), ('RomanceMovies', 'Romance Movies'), ('FantasyMovies', 'Fantasy Movies'), ('AnimationMovies:', 'Animation Movies:')], max_length=250),
        ),
    ]
