# Generated by Django 5.0.2 on 2024-03-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerapp', '0005_alter_genres_movie_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genres',
            name='movie_type',
            field=models.CharField(choices=[('ActionMovies', 'Action Movies'), ('FamilyEntertainment', 'Family Entertainment'), ('HorrorMovies', 'Horror Movies'), ('ThrillerMovies', 'Thriller Movies'), ('ScienceFiction (Sci-Fi) Movies', 'Science Fiction (Sci-Fi) Movies'), ('RomanceMovies', 'Romance Movies'), ('FantasyMovies', 'Fantasy Movies'), ('AnimationMovies:', 'Animation Movies:')], max_length=250, unique=True),
        ),
    ]
