# Generated by Django 5.0.2 on 2024-03-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerapp', '0006_alter_genres_movie_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='language',
            field=models.CharField(choices=[('Malayalam', 'Malayalam'), ('Tamil', 'Tamil'), ('Hindi', 'Hindi'), ('English', 'English'), ('Kannada', 'Kannada')], default='Null', max_length=250),
            preserve_default=False,
        ),
    ]
