# Generated by Django 5.0.2 on 2024-03-09 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registerapp', '0007_movies_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='movie_genres',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='user',
        ),
        migrations.DeleteModel(
            name='Genres',
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
