# Generated by Django 5.0.2 on 2024-03-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerapp', '0008_remove_movies_movie_genres_remove_movies_added_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
