# Generated by Django 5.0.2 on 2024-03-09 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_type', models.CharField(choices=[('ActionMovies', 'Action Movies'), ('FamilyEntertainment', 'Family Entertainment'), ('HorrorMovies', 'Horror Movies'), ('ThrillerMovies', 'Thriller Movies'), ('ScienceFiction (Sci-Fi) Movies', 'Science Fiction (Sci-Fi) Movies'), ('RomanceMovies', 'Romance Movies'), ('FantasyMovies', 'Fantasy Movies'), ('AnimationMovies:', 'Animation Movies:')], max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('language', models.CharField(choices=[('Malayalam', 'Malayalam'), ('Tamil', 'Tamil'), ('Hindi', 'Hindi'), ('English', 'English'), ('Kannada', 'Kannada')], max_length=250)),
                ('director_name', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=250)),
                ('poster', models.ImageField(upload_to='movies')),
                ('hero_name', models.CharField(max_length=250)),
                ('heroin_name', models.CharField(max_length=250)),
                ('movie_description', models.TextField(blank=True)),
                ('released', models.DateField()),
                ('link_trailer', models.URLField(blank=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('movie_genres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_app.genres')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('date_review', models.DateTimeField(auto_now=True)),
                ('rating', models.CharField(max_length=5)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_app.movies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
