# Generated by Django 5.0.2 on 2024-03-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0002_genres_cat_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='trending',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='genres',
            name='cat_img',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
    ]
