# Generated by Django 5.0.2 on 2024-03-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0003_movies_active_movies_trending_alter_genres_cat_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='category',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='movies',
            name='poster',
            field=models.ImageField(blank=True, upload_to='movies'),
        ),
    ]
