# Generated by Django 5.0.2 on 2024-03-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0004_alter_movies_category_alter_movies_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='banner_img',
            field=models.ImageField(blank=True, upload_to='movies'),
        ),
    ]
