# Generated by Django 5.0.2 on 2024-03-21 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0006_remove_movies_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='date_review',
            field=models.DateTimeField(editable=False),
        ),
    ]
